import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/themeProvider";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trust me Bro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>


      <body className={`${inter.className}  min-h-screen flex flex-col` }>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header/>
          <div className="flex-1 flex flex-col">{children}</div>
        </ThemeProvider>
      </body>


    </html>
  );
}
